#[package]
#name = "tuto"
#version = "0.1"
#lean_version = "leanprover-community/lean:3.15.0"
#path = "tutorials/src/solutions"

[package]
name = "logical-verification"
version = "1.0"
lean_version = "leanprover-community/lean:3.15.0"
path = "logical_verification_2020"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "a79304255d549d74e1ab51e087801ad6e75fd434"}
