[package]
name = "logical-verification"
version = "1.0"
lean_version = "leanprover-community/lean:3.5.1"
path = "."

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "2d6556dd69faddc92baacaf97d6c0fb39a804b19"}
